### ISSUE TITLE
Implement support for multiple attributes

### ISSUE THREAD

**Issue by andy5995** [andy5995/canfigger#9]
Looking at [dnsmasq.conf.example](https://github.com/imp/dnsmasq/blob/9560658c5ba27a370b97d30850db474ce67912b7/dnsmasq.conf.example#L167) I see it uses multiple attributes (strings following commas). Right now, canfigger only supports one. I was thinking that would probably be a good change to add.

@eteran, For the [attribute member of the struct](https://github.com/andy5995/canfigger/blob/bfece1066f88c9307ba48b017dcfd75aa3b348ef/canfigger.h#L40), do you think a [c-vector](https://github.com/eteran/c-vector) would be a good choice for the data type?

The other option is I could make another node type that would wind up being a linked list to each attribute in the main node, but that seems like overkill.

What do you think?

**Comment by andy5995** [comment]
I decided to just add another linked list for the attributes and avoid adding external dependencies.

**Comment by eteran** [comment]
@andy5995 c-vector is certainly a reasonable choice anywhere you want a flexible array. However, for your use case, a linked list seems simple enough :-)

**Comment by andy5995** [comment]
Thanks for the feedback @eteran
